stage_premiums:
  outputs:
    dev:
      type: duckdb
      path: C:/Users/TawandaCharuka/Documents/RootProject/db/root_dwh.duckdb
      threads: 4

    prod:
      type: duckdb
      path: prod.duckdb
      threads: 4

  target: dev
